// <auto-generated />
using System;
using BugTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BugTracker.Models.Bug", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int?>("AtribuidoParaId").HasColumnType("int");
                b.Property<bool>("BloqueiaLancamento").HasColumnType("tinyint(1)");
                b.Property<DateTime>("CriadoEm").HasColumnType("datetime(6)");
                b.Property<DateTime?>("AtualizadoEm").HasColumnType("datetime(6)");
                b.Property<string>("Cena").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("Descricao").HasMaxLength(2000).HasColumnType("varchar(2000)");
                b.Property<string>("DetalhesAmbiente").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("FrequenciaReproducao").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Milestone").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("NumeroBuild").HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<string>("Plataforma").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<int>("ProjetoId").HasColumnType("int");
                b.Property<int>("ReportadoPorId").HasColumnType("int");
                b.Property<string>("ResultadoEsperado").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<string>("ResultadoObtido").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<string>("Severidade").IsRequired().HasColumnType("longtext");
                b.Property<string>("Status").IsRequired().HasColumnType("longtext");
                b.Property<string>("TipoBug").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Titulo").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("VersaoJogo").HasMaxLength(30).HasColumnType("varchar(30)");
                b.HasKey("Id");
                b.HasIndex("AtribuidoParaId");
                b.HasIndex("ProjetoId");
                b.HasIndex("ReportadoPorId");
                b.ToTable("Bugs");
            });

            modelBuilder.Entity("BugTracker.Models.Comentario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("BugId").HasColumnType("int");
                b.Property<DateTime>("CriadoEm").HasColumnType("datetime(6)");
                b.Property<string>("Texto").IsRequired().HasColumnType("longtext");
                b.Property<int>("UsuarioId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("BugId");
                b.HasIndex("UsuarioId");
                b.ToTable("Comentarios");
            });

            modelBuilder.Entity("BugTracker.Models.Projeto", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<DateTime>("CriadoEm").HasColumnType("datetime(6)");
                b.Property<string>("Descricao").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("MotorJogo").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Nome").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("PlataformasAlvo").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<string>("VersaoAtual").HasMaxLength(30).HasColumnType("varchar(30)");
                b.HasKey("Id");
                b.ToTable("Projetos");
            });

            modelBuilder.Entity("BugTracker.Models.Usuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<bool>("AceitouTermos").HasColumnType("tinyint(1)");
                b.Property<DateTime?>("AceitouTermosEm").HasColumnType("datetime(6)");
                b.Property<DateTime>("CriadoEm").HasColumnType("datetime(6)");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Perfil").IsRequired().HasColumnType("longtext");
                b.Property<string>("SenhaHash").IsRequired().HasColumnType("longtext");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("BugTracker.Models.Bug", b =>
            {
                b.HasOne("BugTracker.Models.Usuario", "AtribuidoPara")
                    .WithMany("BugsAtribuidos").HasForeignKey("AtribuidoParaId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.HasOne("BugTracker.Models.Projeto", "Projeto")
                    .WithMany("Bugs").HasForeignKey("ProjetoId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("BugTracker.Models.Usuario", "ReportadoPor")
                    .WithMany("BugsReportados").HasForeignKey("ReportadoPorId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("AtribuidoPara");
                b.Navigation("Projeto");
                b.Navigation("ReportadoPor");
            });

            modelBuilder.Entity("BugTracker.Models.Comentario", b =>
            {
                b.HasOne("BugTracker.Models.Bug", "Bug")
                    .WithMany().HasForeignKey("BugId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("BugTracker.Models.Usuario", "Usuario")
                    .WithMany().HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Bug");
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("BugTracker.Models.Projeto", b => { b.Navigation("Bugs"); });
            modelBuilder.Entity("BugTracker.Models.Usuario", b =>
            {
                b.Navigation("BugsAtribuidos");
                b.Navigation("BugsReportados");
            });
#pragma warning restore 612, 618
        }
    }
}
